version: '3'
services:
  app:
    build: .
    environment:
      RAILS_DATABASE_PASSWORD: password
      DATABASE_URL: mysql2://root:password@mysql:3306
    # -p ドライラン:ファイル作成をせず実行。
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    ports:
      - '3000:3000'
    # プロジェクトのカレントディレクトリ(実行場所(?))を/omoidashitterにマウント
    # ⇨ イメージの再構築をしなくてもコードの変更、反映をさせる
    volumes:
      - .:/omoidashitter
    # "リンクするサービス" アプリの実装に当たって必要な外部アプリ(railsの外に存在するmysql)
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    #mysqlnのデータを/var/lib/mysqlに格納(?
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local