twitter: &twitter
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>

development:
  <<: *twitter

test:
  <<: *twitter

production:
  <<: *twitter